Repository LoneStarF13/LoneStar, pull requests merged in 2021-12, with the labels that each got.

#19 new round ping perhaps
  code/__HELPERS/roundend.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/ticker.dm
Labels: Currently Testmerged

#10 enables LOOC while unconscious/dead
  code/modules/client/verbs/looc.dm
Labels: Currently Testmerged

#8 Back to Basics, the original 5mm assault carbine is now undergoing trials
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: Currently Testmerged

#24 Fixes the chinese uniforms, makes them use the right sprites, and generally cleans up the code for them.
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/under/f13.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Currently Testmerged

#9 stim fix for frok
  code/modules/fallout/reagents/medicines.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Currently Testmerged

#34 den use rings instead of tattoos
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/job_types/wasteland.dm
Labels: Testmerge Candidate

#39 Adds low surgery skill to corpsmen.
  code/modules/jobs/job_types/ncr.dm
Labels: Currently Testmerged

#36 BRINGS BACK THE FLIP EMOTE
  code/modules/mob/emote.dm
Labels: Changes Requested

#41 U.S. Army and new Police Uniforms.
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/under/f13.dm
  icons/fallout/clothing/hats.dmi
  icons/fallout/clothing/suits_cosmetic.dmi
  icons/fallout/clothing/uniforms.dmi
  icons/fallout/onmob/clothes/head.dmi
  icons/fallout/onmob/clothes/suit_cosmetic.dmi
  icons/fallout/onmob/clothes/uniform.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Testmerge Candidate

#43 new round ping but the right way this time
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/general.dm
Labels: Currently Testmerged

#16 follower base hotfix
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Currently Testmerged

#15 not awful version of the powerfist pr
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/game/objects/items/melee/f13powerfist.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/legion.dm
Labels: Currently Testmerged

#31 just adds a recipe book for nuka cola drinks
  code/game/objects/items/manuals.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/dinnerware.dm
Labels: Currently Testmerged

#57 comments out pa helmet deflection
  code/modules/clothing/head/f13head.dm
Labels: Testmerge Candidate

#46 Added new NCR base
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Currently Testmerged

#21 grug says allow tribals to use spirit stones to communicate, grug also says tribals shouldnt waste deathclaw skins on combat armor
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/granters.dm
  code/modules/jobs/job_types/tribals.dm
Labels: Currently Testmerged

#22 Follower signature weapons, less-lethal laser and recharger laser
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  icons/fallout/objects/guns/energy.dmi
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
Labels: Currently Testmerged

#30 fucks combat stims
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Currently Testmerged

#29 Minigun
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/guns/ballistic/minigun.dm
  fortune13.dme
Labels: Currently Testmerged

#48 Port Party
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/ladders.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  icons/turf/overlays.dmi
Labels: Currently Testmerged

#68 Brotherhood surface elevator
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/shuttles/entrance_elevator.dmm
Labels: Currently Testmerged
