Repository LoneStarF13/LoneStar, pull requests merged in 2022-02, with the labels that each got.

#265 Whitelisting preliminary.
  code/modules/jobs/job_whitelist.dm
  code/modules/jobs/jobs.dm
Labels: Currently Testmerged

#272 Revamps the Police Station and junk-ifies most bathrooms
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Currently Testmerged

#285 crossbow crafting fix
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/modules/jobs/job_types/legion.dm
Labels: Currently Testmerged

#284 Big Port Batch 2 [Ready to Testmerge]
  .github/ISSUE_TEMPLATE/bug_report.md
  code/__DEFINES/say.dm
  code/__HELPERS/_lists.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/datums/components/crafting/glassware/glassware.dm
  code/datums/components/crafting/glassware/lens_crafting.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/procedural_mapping/mapGenerators/repair.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/rags.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/surgery/dental_implant.dm
Labels: Currently Testmerged

#268 light armor buff and minor bugfixes
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/suits/f13suits.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/hoboguns.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
Labels: Currently Testmerged

#297 Stimpaks (and Supers) make you hungry, and poison you if you're starving.
  code/modules/fallout/reagents/medicines.dm
Labels: Currently Testmerged

#299 Fermichem recipes for Super Stimfluid, Jet, Turbo, Psycho, Med-X and Buffout + other chem changes
  code/datums/materials/basemats.dm
  code/modules/fallout/obj/food_and_drinks/wastefood.dm
  code/modules/fallout/obj/smelling_salts.dm
  code/modules/fallout/reagents/alcohol.dm
  code/modules/fallout/reagents/drugs.dm
  code/modules/fallout/reagents/teas.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/agave.dm
  code/modules/hydroponics/grown/broc.dm
  code/modules/hydroponics/grown/buffalogourd.dm
  code/modules/hydroponics/grown/coyotetobacco.dm
  code/modules/hydroponics/grown/datura.dm
  code/modules/hydroponics/grown/feracactus.dm
  code/modules/hydroponics/grown/horsenettle.dm
  code/modules/hydroponics/grown/mesquite.dm
  code/modules/hydroponics/grown/mutfruit.dm
  code/modules/hydroponics/grown/pinyon.dm
  code/modules/hydroponics/grown/prickly.dm
  code/modules/hydroponics/grown/punga.dm
  code/modules/hydroponics/grown/tato.dm
  code/modules/hydroponics/grown/xander.dm
  code/modules/hydroponics/grown/yucca.dm
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
  fortune13.dme
Labels: Currently Testmerged

#301 multi-z shit, areas fix included
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  icons/obj/stairs.dmi
Labels: Currently Testmerged

#292 veteran ranger buff pr (shotgun loadout)
  code/modules/jobs/job_types/ncr.dm
Labels: Currently Testmerged

#327 shield fix
  code/game/objects/items/shields.dm
Labels: Type: Fix

#329 stimpak crafting fixes
  code/datums/components/crafting/recipes/recipes_medicine.dm
Labels: Type: Fix

#303 Heavy Duty Sheath, Ranger Cape Fix, Crafting Additions
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
Labels: Code: Addition, Type: Fix

#331 reduces the rate of nutrition loss from stimpaks
  code/modules/fallout/reagents/medicines.dm
Labels: Type: Balancing

#300 follower vending update
  code/modules/WVM/wvm.dm
Labels: Status: Testmerged, Type: Balancing

#315 Legion Immunes
  _maps/map_files/DR2sPrefabs.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/jobs.dm
  icons/fallout/clothing/hats.dmi
  icons/fallout/onmob/clothes/head.dmi
Labels: Status: Testmerged, Code: Addition, Type: Balancing

#325 let there be boom
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Status: Testmerged, Code: Addition, Type: Balancing

#286 armor, loadouts, balancing, guns, oh my
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/followers.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/energy/plasmaf13.dm
  code/modules/projectiles/projectile/beams.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Status: Testmerged, Type: Balancing

#334 Remove sprinting from the movement sprite.
  icons/fallout/UI/buttons_fallout2.dmi
Labels: Type: Sprites, No Code

#326 tribal buffs ('new' arrow type, support for faction damage bonus on projectiles)
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/modules/projectiles/ammunition/caseless/arrow.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/reusable/arrow.dm
Labels: Code: Addition, Type: Balancing

#338 Fixes binos, maybe.
  code/game/objects/items/binoculars.dm
Labels: Status: Testmerged, Code: Rework, Type: Fix

#310 show your love for nuka cola
  code/__DEFINES/food.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/mood_events/drug_events.dm
  code/datums/traits/good.dm
  code/modules/fallout/reagents/alcohol.dm
  code/modules/fallout/reagents/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Labels: Status: Testmerged, Code: Addition

#320 Adds a Second Floor to the Yuma Bank
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Status: Testmerged, Type: Map, No Code

#337 autoaxe/steelsaw buffs/changes
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/objects/items/melee/f13twohanded.dm
Labels: Code: Rework, Type: Balancing

#356 fixes vet legionaire not getting a .357 revolver
  code/modules/jobs/job_types/legion.dm
Labels: Type: Fix

#345 Port of the port "Let Me Tell You A Story"
  code/modules/mob/living/carbon/alien/alien.dm
Labels: technical debt, Type: Fix

#349 Ports some hallucination tweaks
  code/modules/flufftext/Hallucination.dm
Labels: technical debt, Type: Fix

#342 Legion Boomies
  code/modules/jobs/job_types/legion.dm
Labels: Code: Addition

#340 fortnite nerf (removes unsupported lattice building)
  code/game/turfs/openspace/openspace.dm
Labels: Code: Removal, Type: Balancing

#339 weekly armor update: laser edition
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/suits/f13suits.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/fallout/misc/gang_items.dm
  code/modules/fallout/misc/gangs.dm
  code/modules/jobs/job_types/wasteland.dm
Labels: Type: Balancing

#343 New Loadout Items (Smokers/Army Officers Rejoice)
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/hands.dm
Labels: Code: Addition

#344 Port of the port "Makes the microwave cleanable by the damp rag"
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Labels: technical debt, Code: Addition

#346 Port of you can now shove yourself up on any intent
  code/modules/mob/living/carbon/human/species.dm
Labels: technical debt, Code: Rework

#347 Port of a port of breaking a mirror now gives you a bad omen
  code/game/objects/structures/mirror.dm
Labels: technical debt, Code: Addition

#348 Ports stripping a disconnected player will tell them when they come back
  code/__DEFINES/inventory.dm
  code/__HELPERS/_lists.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/living/living.dm
Labels: technical debt, Code: Addition

#357 legion explorer sniper is dead, long live legion explorer enfielder
  code/modules/jobs/job_types/legion.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  icons/fallout/objects/guns/ballistic.dmi
Labels: Type: Balancing

#361 heavily nerfs synthtissue
  code/__DEFINES/reagents.dm
  code/game/objects/items/defib.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Type: Balancing

#341 neck tilting (people can look up now)
  code/modules/mob/living/living.dm
Labels: Code: Addition

#358 Ranger Station Oscar
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
Labels: Type: Map, No Code

#365 buffs medicine/drug yield from fermichem recipes heavily
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Type: Balancing

#353 bow rework (functionally a nerf to all non-tribals)
  code/__DEFINES/traits.dm
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/game/objects/items/granters.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/boxes_magazines/internal/bow.dm
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/bow.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/hoboguns.dm
  icons/obj/guns/projectile.dmi
Labels: Code: Rework, Type: Balancing

#354 yuma book club: a literate wasteland is a happy wasteland
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Code: Addition

#370 ability to cancel actions (port)
  code/modules/keybindings/keybind/living.dm
Labels: Code: Addition

#372 armor value examining fixes
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/f13armor.dm
Labels: Type: Fix

#381 Flowers Update + Pumpkins + Crowns + Misc
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/pumpkin.dm
  code/modules/vending/megaseed.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/inhands/misc/food_lefthand.dmi
  icons/mob/inhands/misc/food_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/food/soupsalad.dmi
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/harvest.dmi
Labels: Type: Sprites, Code: Addition

#377 people now show how long they've been afk/disconnected for on examine, offline indicator no longer appears on mobs that may be revivable but with no ghost in corpse, recusitation message clarification
  code/__DEFINES/mobs.dm
  code/game/data_huds.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
Labels: Status: Testmerged, Code: Addition

#392 Changes the sprite of some of the legion armors Mk.2
  icons/fallout/clothing/armored_light.dmi
  icons/fallout/clothing/armored_medium.dmi
  icons/fallout/onmob/clothes/armor_light.dmi
  icons/fallout/onmob/clothes/armor_medium.dmi
  icons/fallout/onmob/clothes/head.dmi
Labels: Type: Sprites, No Code

#385 Lets Rangers get utility vests from loadout.
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Code: Addition

#375 sprite fix,BAR full-auto stats,fixes police rifle/assault carbine
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/turf/floors/carpet_vault.dmi
Labels: Type: Sprites, Type: Balancing

#374 Adds the Bone Dancer tribal loadout + objects
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/medium_armor.dm
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/wasteland.dm
  icons/fallout/onmob/weapons/shields_lefthand.dmi
  icons/fallout/onmob/weapons/shields_righthand.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Status: Testmerged, Type: Sprites, Code: Addition, Type: Balancing

#379 alternate pathway for making most drugs
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Status: Testmerged, Type: Balancing

#382 med-sci treasure: science is its own reward
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Status: Testmerged, Code: Addition, Type: Balancing

#383 primitive chemistry/grinder improvements
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Status: Testmerged, Type: Balancing

#387 sadist loadout tribal quiver>belt
  code/modules/jobs/job_types/wasteland.dm
Labels: Status: Testmerged, Type: Balancing

#386 salvaging buffs
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/old/Dungeons.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  code/datums/components/crafting/recipes/recipes_explosives.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/crafting/items.dm
  code/modules/fallout/obj/crafting.dm
  code/modules/fallout/obj/spawners/lootdrops.dm
  code/modules/vehicles/rubbish.dm
  testing.dmm
Labels: Status: Testmerged, Type: Balancing

#394 .45 LC speed loader on holster
  code/game/objects/items/storage/belt.dm
Labels: Code: Addition, Type: Balancing

#391 loreworthy 9mm+ slight cut to gunbloat
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/WVM/wvm.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
Labels: Testmerge Candidate, Code: Removal, Type: Balancing
