Repository LoneStarF13/LoneStar, pull requests merged in 2022-01, with the labels that each got.

#33 come in watson, I need you...to test out these new intercoms
  code/game/objects/items/devices/radio/intercom.dm
  icons/obj/radio.dmi
Labels: Currently Testmerged

#35 an explosion pr that doesn't break
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Currently Testmerged

#45 The Great Tribal Rework (Ready for Testing)
  _maps/map_files/Pahrump/Dungeons.dmm
  code/__DEFINES/jobs.dm
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/autolathe.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/clothing/suits/light_armor.dm
  code/modules/fallout/misc/gangs.dm
  code/modules/fallout/misc/tribes.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/hydroponics/gene_modder.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/jobs/job_types/tribals.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/jobs/jobs.dm
  fortune13.dme
Labels: Currently Testmerged

#56 Bruh Gun moment
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: Currently Testmerged

#64 disables wallstuns
  code/modules/mob/living/carbon/carbon.dm
Labels: Currently Testmerged

#65 medx nerf
  code/modules/fallout/reagents/medicines.dm
Labels: Currently Testmerged

#69 Legion Armor Conversions
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/legion.dm
Labels: Currently Testmerged

#71 Removed R93's burst
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Currently Testmerged

#72 Adjusted Khan slots, loadout, and timelock
  code/modules/jobs/job_types/wasteland.dm
Labels: Currently Testmerged

#77 grenades and rocket launchers + minigun backpack click change
  code/game/machinery/computer/arcade/minesweeper.dm
  code/game/objects/items/grenades/f13grenade.dm
  code/game/objects/items/shrapnel.dm
  code/modules/projectiles/ammunition/caseless/rocket.dm
  code/modules/projectiles/guns/ballistic/laser_gatling.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
  code/modules/projectiles/projectile/special/rocket.dm
  fortune13.dme
Labels: Currently Testmerged

#98 Khan map file fix
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/game/objects/items/fallout13misc.dm
  fortune13.dme
  icons/obj/flags.dmi
Labels: Currently Testmerged

#128 Medicine artwork + QoL
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/f13storage.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/fallout/obj/smelling_salts.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
  icons/fallout/objects/medicine/chemical.dmi
  icons/fallout/objects/medicine/drugs.dmi
  icons/fallout/objects/medicine/legacy.dmi
  icons/fallout/objects/medicine/primitivedefib.dmi
  icons/fallout/objects/storage.dmi
  icons/obj/fallout/smelling_salts.dmi
Labels: Testmerge Candidate

#104 lore-based wattz2000 and finally fixing the long, sad, saga of the compliance regulator
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Testmerge Candidate

#86 Yuma Wasteland Supply inc. is proud to announce their Vending machine based economic stimulus plan
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/briefcase.dm
  code/modules/WVM/wmv_buyer.dm
  code/modules/WVM/wvm.dm
Labels: Testmerge Candidate

#106 Tesla Cannon
  code/modules/projectiles/ammunition/energy/tesla.dm
  code/modules/projectiles/guns/energy/tesla.dm
  code/modules/projectiles/projectile/energy/tesla.dm
  fortune13.dme
Labels: Testmerge Candidate

#117 Den Map Changes
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Currently Testmerged

#115 fix bulk stim crafting because byond dumb (for real this time I promise)
  code/game/objects/items/storage/f13storage.dm
Labels: Currently Testmerged

#126 Brotherhood Faction Armour
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/jobs/job_types/bos.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged

#134 Armor Conversion Rework
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/game/objects/items/stacks/crafting.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/suits/f13suits.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/job_types/wasteland.dm
Labels: Currently Testmerged

#136 After an arduous testing phase, the Followers have approved the AEP5-Compliance Regulator for standard issue
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/guncase.dm
  code/modules/jobs/job_types/followers.dm
  icons/fallout/objects/guns/energy.dmi
Labels: Currently Testmerged

#142 BoS Timelocks +2 Knight Slots for SK/K, Add Ripper & BPF
  code/modules/jobs/job_types/bos.dm
Labels: Currently Testmerged

#146 RCW Display fix
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Currently Testmerged

#147 Goodbye Vault 134, unbalanced POS
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Currently Testmerged

#149 Rock-It-Launcher
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/fallout/obj/rockitlauncher.dm
  fortune13.dme
  icons/fallout/objects/guns/rockitlauncher.dmi
  icons/mob/clothing/back.dmi
  sound/f13weapons/rockitlauncher_fire.ogg
Labels: Currently Testmerged

#152 Toilets and sinks
  code/datums/components/crafting/recipes/recipes_misc.dm
Labels: Currently Testmerged

#97 Added a Fire Station
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Currently Testmerged

#127 outlaws are armed and dangerous, black market armaments re-directed armaments away from the den
  code/modules/fallout/misc/gang_items.dm
  code/modules/fallout/misc/gangs.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Currently Testmerged

#153 the great de-spacening
  code/controllers/subsystem/mapping.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mapping/space_management/space_transition.dm
  code/modules/shuttle/elevator.dm
  config/config.txt
  config/motd.txt
Labels: Currently Testmerged, Massive Change

#155 Bombs grenades bugfixes rocket launchers & pre war alloy
  code/__DEFINES/construction.dm
  code/__DEFINES/traits.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_explosives.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/datums/components/remote_materials.dm
  code/datums/traits/good.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/grenades/f13grenade.dm
  code/game/objects/items/grenades/ghettobomb.dm
  code/modules/WVM/wvm.dm
  code/modules/crafting/items.dm
  code/modules/fallout/obj/crafting.dm
  code/modules/fallout/obj/explosives.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/misc/grenade_launcher.dm
  code/modules/projectiles/projectile/bullets/grenade.dm
  code/modules/projectiles/projectile/special/rocket.dm
  code/modules/research/designs/smelting_designs.dm
  code/modules/research/techweb/_techweb_node.dm
  fortune13.dme
Labels: Testmerge Candidate

#157 CZ53 Personal Minigun/Gatling Laser Update/NCR-BoS Loadout Update
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/boxes_magazines/external/lmg.dm
  code/modules/projectiles/boxes_magazines/internal/misc.dm
  code/modules/projectiles/guns/ballistic/laser_gatling.dm
  code/modules/projectiles/guns/ballistic/minigun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs/ammolathe_designs.dm
  fortune13.dme
  icons/fallout/objects/guns/ammo.dmi
  icons/obj/ammo.dmi
Labels: Currently Testmerged

#156 guns show up on your back now
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/bow.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt_mirror.dmi
Labels: Currently Testmerged

#162 made NCR dirty, followers get spare equipment, you can now mulch guns for caps
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/modules/WVM/wmv_buyer.dm
  code/modules/WVM/wvm.dm
Labels: Currently Testmerged

#169 Farming Stuff
  code/datums/components/crafting/recipes/recipes_assemblies.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/loom.dm
  code/modules/clothing/gloves/f13gloves.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/suits/f13suits.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/fallout/obj/structures/haycrafts.dm
  code/modules/farming/farming_structures.dm
  code/modules/farming/farming_tools.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_dispenser.dm
  fortune13.dme
  icons/fallout/clothing/belts.dmi
  icons/fallout/clothing/gloves.dmi
  icons/fallout/clothing/suits_utility.dmi
  icons/fallout/farming/farming_structures.dmi
  icons/fallout/farming/farming_tools.dmi
  icons/fallout/onmob/clothes/hand.dmi
  icons/fallout/onmob/clothes/suit_utility.dmi
  icons/fallout/onmob/tools/farming_lefthand.dmi
  icons/fallout/onmob/tools/farming_righthand.dmi
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/items_and_weapons.dmi
Labels: Currently Testmerged

#170 Buff Salvaging because its PAIN
  code/modules/jobs/job_types/legion.dm
  code/modules/vehicles/rubbish.dm
Labels: Currently Testmerged

#173 barbs-your-wire introduces revolutionary new war crimes
  code/game/objects/items/stacks/rods.dm
  code/modules/fallout/obj/structures/obstacle.dm
Labels: Currently Testmerged

#148 The Tribes of the West
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/datums/components/crafting/recipes/recipes_explosives.dm
  code/datums/components/crafting/recipes/recipes_forge.dm
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/melee/f13twohanded.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/under/f13.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_donut.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pies_sweets.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/fallout/objects/melee/melee.dmi
  icons/fallout/onmob/weapons/melee2h_lefthand.dmi
  icons/fallout/onmob/weapons/melee2h_righthand.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/deathclaw.dmi
  icons/mob/wastemobs.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Changes Requested

#177 propaganda eye bot is silent now
  code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
Labels: Currently Testmerged

#182 Dirt adjust
  code/modules/fallout/turf/ground.dm
  icons/fallout/turfs/dirt.dmi
  icons/fallout/turfs/gravel.dmi
  icons/fallout/turfs/houseruin.dmi
  icons/fallout/turfs/savannah.dmi
  icons/fallout/turfs/wood_floor.dmi
Labels: Currently Testmerged

#172 Removes most dense rock from the surface map
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/game/turfs/simulated/minerals.dm
Labels: Currently Testmerged

#185 oasis prepares for war
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/granters.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/oasis.dm
  icons/fallout/clothing/helmets.dmi
  icons/fallout/onmob/clothes/helmet.dmi
  icons/mob/clothing/belt_mirror.dmi
Labels: Currently Testmerged

#193 UI alpha adjust
  code/__HELPERS/type2type.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screen_objects/sprint.dm
  code/modules/tooltip/tooltip.html
  icons/fallout/UI/buttons_fallout2.dmi
  icons/fallout/UI/screen_fallout2.dmi
  icons/fallout/UI/screen_fallout2_dark.dmi
  icons/fallout/UI/screen_fallout2_pale.dmi
  icons/mob/screen_gen.dmi
Labels: Currently Testmerged

#196 Ports Colormates (take 2) [Ready to Test Merge]
  code/__HELPERS/icons.dm
  code/__HELPERS/matrices.dm
  code/game/machinery/colormate.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_alert.dm
  fortune13.dme
  icons/obj/vending.dmi
  tgui/packages/tgui/interfaces/Colormate.js
  tgui/public/tgui.bundle.js
Labels: Currently Testmerged

#198 easy pete delivers some dynamite to yuma
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/game/objects/items/grenades/f13grenade.dm
  icons/fallout/objects/guns/explosives.dmi
Labels: Currently Testmerged

#213 hides lewd stuff + mkultra no longer available through chem
  code/modules/arousal/arousal.dm
  code/modules/arousal/genitals.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Currently Testmerged

#199 Mob organize
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/fallout/obj/structures/simple_door.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mob/living/simple_animal/friendly/animalfriendly.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/animalhostile.dm
  code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
  code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/insects.dm
  code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
  code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/research/bepis.dm
  fortune13.dme
  icons/fallout/clothing/mantles.dmi
  icons/fallout/mobs/animal.dmi
  icons/fallout/mobs/animals/antqueen.dmi
  icons/fallout/mobs/animals/farmanimals.dmi
  icons/fallout/mobs/animals/insects.dmi
  icons/fallout/mobs/animals/mirelurks.dmi
  icons/fallout/mobs/animals/nightstalker.dmi
  icons/fallout/mobs/animals/wasteanimals.dmi
  icons/fallout/mobs/hostile_east.dmi
  icons/fallout/mobs/hostile_general.dmi
  icons/fallout/mobs/legacymobs.dmi
  icons/fallout/mobs/mob_adminbus.dmi
  icons/fallout/mobs/mob_friendly.dmi
  icons/fallout/mobs/monsters/deathclaw.dmi
  icons/fallout/mobs/monsters/freaks.dmi
  icons/fallout/mobs/monsters/tunnelers.dmi
  icons/fallout/mobs/monsters/wanamingo.dmi
  icons/fallout/mobs/robots.dmi
  icons/fallout/mobs/robots/eyebots.dmi
  icons/fallout/mobs/robots/protectrons.dmi
  icons/fallout/mobs/robots/robot_enclave.dmi
  icons/fallout/mobs/robots/robot_general.dmi
  icons/fallout/mobs/robots/wasterobots.dmi
  icons/fallout/mobs/robots/weirdrobots.dmi
  icons/fallout/onmob/clothes/mantle.dmi
  icons/fallout/structures/doors.dmi
  icons/mob/MOB2.dmi
  icons/mob/animal.dmi
  icons/mob/animalC.dmi
  icons/mob/animalD.dmi
  icons/mob/greengecko.dmi
  icons/mob/robots.dmi
  icons/mob/wastemobs.dmi
  icons/mob/wastemobslong.dmi
Labels: Testmerge Candidate

#190 The return of twohanders
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/f13twohanded.dm
  icons/fallout/objects/melee/melee.dmi
  icons/fallout/objects/melee/twohanded.dmi
  icons/fallout/onmob/backslot_bags.dmi
  icons/fallout/onmob/backslot_weapon.dmi
  icons/fallout/onmob/weapons/64x64_lefthand.dmi
  icons/fallout/onmob/weapons/64x64_righthand.dmi
  icons/fallout/onmob/weapons/melee2h_lefthand.dmi
  icons/fallout/onmob/weapons/melee2h_righthand.dmi
  icons/mob/clothing/back.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
Labels: Currently Testmerged

#188 Full Auto
  code/_onclick/drag_drop.dm
  code/modules/projectiles/gun.dm
  icons/effects/mouse_pointers/weapon_pointer.dmi
Labels: Testmerge Candidate

#187 Multi-Z
  _maps/map_files/Pahrump/Pahrump-Above-3.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/pahrump.json
  code/__DEFINES/maps.dm
  code/__HELPERS/level_traits.dm
  code/game/objects/items/binoculars.dm
  code/game/turfs/openspace/openspace.dm
  code/modules/fallout/turf/ground.dm
Labels: Testmerge Candidate

#231 Removes Slowdown on Roads(and most tiles), Reduces Sand Slowdown
  code/modules/fallout/turf/ground.dm
Labels: Currently Testmerged

#168 slow and methodical armor, gun, and bullet change. let the linearmor die, kill it if you have to
  code/datums/components/armor_plate.dm
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/suits/f13suits.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
  code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/minigun.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  icons/fallout/objects/melee/melee.dmi
Labels: Testmerge Candidate, Massive Change

#233 Fix and Additions Batch [Ready to TM]
  code/__DEFINES/_flags/_flags.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/say.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/input.dm
  code/datums/explosion.dm
  code/datums/status_effects/status_effect.dm
  code/game/machinery/colormate.dm
  code/game/objects/empulse.dm
  code/game/objects/obj_defense.dm
  code/game/say.dm
  code/game/turfs/change_turf.dm
  code/modules/admin/verbs/individual_logging.dm
  code/modules/admin/verbs/pray.dm
  code/modules/cargo/exports.dm
  code/modules/client/verbs/looc.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/f13.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/living_active_parry.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_helpers.dm
  code/modules/smithing/finished_items.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/unit_tests/crafting_recipes.dm.txt
  code/modules/vehicles/wheelchair.dm
  interface/stylesheet.dm
  sound/effects/ding.ogg
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/index.js
  tgui/packages/tgui/styles/themes/clockcult.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tools/ci/check_grep.sh
Labels: Currently Testmerged

#206 Removal of mapped high/very/super weapon spawners, replacement with component spawners, faction support recipes
  _maps/RandomZLevels/VR/yuma_VR.dmm
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/templates/dungeons/north_bunker_1.dmm
  _maps/map_files/templates/dungeons/north_bunker_2.dmm
  _maps/map_files/templates/dungeons/north_sewer_1.dmm
  _maps/map_files/templates/dungeons/oasis_bunker_1.dmm
  _maps/map_files/templates/dungeons/oasis_bunker_2.dmm
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/ammunition/caseless/arrow.dm
  code/modules/projectiles/boxes_magazines/internal/bow.dm
  code/modules/projectiles/guns/ballistic/bow.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasmaf13.dm
  code/modules/projectiles/projectile/reusable/arrow.dm
  fortune13.dme
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Currently Testmerged

#209 new year, new mayoral loadouts
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/projectiles/ammunition/caseless/ballistic.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  icons/fallout/objects/guns/ammo.dmi
  icons/fallout/objects/guns/ballistic.dmi
  icons/obj/guns/projectile.dmi
Labels: Currently Testmerged

#251 Trashcan and his friends
  code/datums/components/crafting/recipes/recipes_explosives.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/fallout/misc/gang_items.dm
  code/modules/fallout/misc/gangs.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/power/cell.dm
  icons/fallout/clothing/khans.dmi
  icons/fallout/objects/crates.dmi
  icons/fallout/objects/powercells.dmi
  icons/fallout/onmob/clothes/khaans.dmi
  icons/mob/hair_extensions.dmi
  icons/mob/human_face.dmi
Labels: Currently Testmerged

#252 Improvised bomb fuzing tweak
  code/game/objects/items/grenades/ghettobomb.dm
Labels: Currently Testmerged

#254 Re operation table
  icons/obj/surgery.dmi
Labels: Currently Testmerged

#256 Mob Justice
  code/game/objects/effects/decals/remains.dm
  code/modules/mob/living/simple_animal/friendly/animalfriendly.dm
  code/modules/mob/living/simple_animal/hostile/animalhostile.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/mob/living/simple_animal/hostile/f13/wolf.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
  code/modules/mob/living/simple_animal/hostile/synth.dm
  icons/fallout/mobs/animal.dmi
  icons/fallout/mobs/animals/dogs.dmi
  icons/fallout/mobs/animals/yaoguai.dmi
  icons/fallout/mobs/animals/yaoguai_2.dmi
  icons/fallout/mobs/behemoth.dmi
  icons/fallout/mobs/hostile_feralghoul.dmi
  icons/fallout/mobs/humans/fallout_npc.dmi
  icons/fallout/mobs/humans/ghouls.dmi
  icons/fallout/mobs/humans/raider.dmi
  icons/fallout/mobs/legacymobs.dmi
  icons/fallout/mobs/mob_drops.dmi
  icons/fallout/mobs/mob_friendly.dmi
  icons/fallout/mobs/nests.dmi
  icons/fallout/mobs/npc/mobnpc.dmi
  icons/fallout/mobs/supermutant.dmi
  icons/fallout/mobs/supermutant_dead.dmi
  icons/mob/Dead_Behemoth.dmi
  icons/mob/animal.dmi
  icons/mob/frozenmob.dmi
  icons/mob/wastemobs.dmi
Labels: Currently Testmerged
